### ISSUE TITLE
Convert `page.preview` to `page.excerpt`

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.org#43]
Following up on our discussion in #36, `page.excerpt` is the standard way (and automatically filled if you leave it blank) for displaying a short preview of a blogpost.

Appears in these blogposts as far as I see:

```
_posts/2016-07-23-how-to-participate-in-the-global-day-of-coderetreat-2016.html
_posts/2017-07-17-deprecating-the-ning-social-network.md
_posts/2016-04-09-announcing-global-day-of-coderetreat-2016.html
_posts/2015-10-13-three-simulations-in-one-45-min-sprint.html
_posts/2016-09-21-celebrating-100-gdcr-events-all-over-the-world-with-a-special-sur.html
_posts/2015-07-20-self-organizing-team-2-footballs.html
_posts/2016-04-25-the-first-global-day-of-coderetreat-in-nokia-cd-site.html
_posts/2015-09-02-enabling-constraints.html
```

A simple `sed` should be enough, just need to make sure that the template is changed and it doesn't break things.

**Comment by toubou91** [comment]
I am not sure I fully understand.

`page.excerpt` (just read about it) is indeed the standard way, but then I see no occurence of it in this project.
That said, may I ask whether you mean to just rename the `preview` property of each post to `excerpt`?

So that the following:
```
---
preview: The <strong>Saturday, October 22nd</strong> is getting closer and with it the Global Day of Coderetreat 2016. It's now the time to consider how you'll participate in the event. Here are the possibilities
---
```

will be converted to:

```
---
excerpt: The <strong>Saturday, October 22nd</strong> is getting closer and with it the Global Day of Coderetreat 2016. It's now the time to consider how you'll participate in the event. Here are the possibilities
---
```

Regards,
Thodoris

**Comment by davidalpert** [comment]
@rradczewski I'm not sure I understand either. AFAIK in the liquid templating language it's possible to auto-generate a preview/excerpt from a jekyll blog post using the [`truncatewords` function](https://shopify.github.io/liquid/filters/truncatewords/) like in [this template](https://github.com/nandomoreirame/zetsu/blob/master/_includes/post.html#L10)

It seems that approach might be sufficient unless the excerpts are custom-written rather than the leading # number of words, but even so, the leading 30 words or so of each post is likely sufficient, no?

**Comment by mikepc** [comment]
I think the source of the confusion is that how the preview is being generated isn't really the issue. The core issue is that the contract for the blog post is simply changing from *preview* to *excerpt* and the work is basically just to make sure it still works.
